project:
  type: website
  output-dir: docs

website:
  title: "ht-oliver.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
      - icon: github
        href: https://github.com/ht-oliver/mysite


format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full
    mainfont: Nunito
    

editor: visual

